title: Ina Tsetsova
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Ina Tsetsova. I'm a dev, currently based in London. This blog is about the many random things I'm learning and doing. Thanks for stopping by :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tsetsova.github.io./" # the base hostname & protocol for your site
twitter_username: inatsetsova
github_username:  tsetsova

# Build settings
markdown: kramdown
